### ISSUE TITLE
Connecting the cube to Zigbee2MQTT

### ISSUE THREAD

**Issue by olegkron** [artkli/cube#1]
Hello, 
How did you manage to connect the cube to the Zigbe2Mqtt? As far as I'm aware you have to use the Aqara hub for obtaining the cube's token beforehand. Did you use the aqara hub for that? 
Without modifying the configuration.yaml in my Home Assistant I can't get it to pair.

After some time it throws me an error:
zigbee2mqtt:error 2020-07-04 16:03:47: Failed to interview '0x00158d00042204a5', device has not successfully been paired

All I'm asking is if I need to get the Aqara hub just to be able to obtain the token or if there are any other ways to get it without having to buy the hub.
Thanks in advance for the clarification!

**Comment by artkli** [comment]
After hardware preparation (Flashing) [https://gadget-freakz.com/diy-zigbee-gateway/] the configuration in the configuration.yaml file looks like this :

```
# Home Assistant integration (MQTT discovery)
homeassistant: false

# allow new devices to join
#permit_join: true
permit_join: false

# MQTT settings
mqtt:
  # MQTT base topic for zigbee2mqtt MQTT messages
  base_topic: zigbee2mqtt
  # MQTT server URL
  server: 'mqtt://localhost'
  # MQTT server authentication, uncomment if required:
  # user: my_user
  # password: my_password

# Serial settings
serial:
  # Location of CC2531 USB sniffer
  disable_led: true
  port: /dev/ttyACM0

devices:
  '0x00158d000xxxxxxx':
    friendly_name: cube
    retain: false
  '0x00158d000yyyyyyy':
    friendly_name: temp
    retain: false

```
